site_name: Dr.407酱的食用指南w
extra_css:
  - stylesheets/extra.css
theme:
  font: false
  name: 'mkdocs'
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
      - navigation.instant
  palette:
      primary: black
      scheme: slate